version: '3.7'

services:
  django:
    build:
      context: /backend
      dockerfile: Dockerfile
    ports:
      - "8001:8001"
    command: python3 manage.py runserver 0.0.0.0:8001
    networks:
      - resolute

  vue.js:
    build:
      context: /frontend-vue
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    networks:
      - resolute

networks:
  resolute:
    name: resolute